In [1]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
print(f"Versão do NumPy: {np.__version__}")

Versão do NumPy: 2.0.2


### 2. Criando Arrays(Vetores e Matrizes)

A principal estrutura de dados do NumPy é o ndarray

In [3]:
# Criando um array 1D (Vetor) a partir de uma lista Python
vetor = np.array([1, 2, 3, 4, 5])
print("Vetor 1D:", vetor)

# Criando um array 2D (Matriz) a partir de uma lista de listas
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(f"\n {matriz[0, 0]}")
print("\nMatriz 2D:\n", matriz)

Vetor 1D: [1 2 3 4 5]

 1

Matriz 2D:
 [[1 2 3]
 [4 5 6]]


### Funções úteis para criação de Arrays

O NumPy possui funções nativas para gerar arrays comuns rapidamente, o que é muito útil para inicializar pesos em Redes Neurais, por exemplo.

In [5]:
# Array de zeros
zeros = np.zeros((2,3)) # 2 linhas e 3 colunas
print(f"Zeros:\n {zeros}")

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# Array de uns
uns = np.ones((3, 3))
print(f"\nUns:\n {uns}")


Uns:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
# Array com uma sequência de números (similar ao range() do Python)
sequencia = np.arange(0, 10, 2) # Início, Fim (exclusivo), Passo
print(f"\nSequência (arange): {sequencia}")


Sequência (arange): [0 2 4 6 8]


In [8]:
# Valores linearmente espaçados
espacados = np.linspace(0, 1, 5) # 5 valores entre 0 e 1
print(f"\nLinspace: {espacados}")


Linspace: [0.   0.25 0.5  0.75 1.  ]


### 3. Inspecionando Arrays

É crucial saber o tamanho e o formato dos seus dados, especialmente ao preparar datasets para mineração de dados.

In [9]:
print(f"Formato (shape): {matriz.shape}") # (linhas, colunas)
print(f"Dimensões (ndim): {matriz.ndim}") # Número de dimensões
print(f"Tamanho total (size): {matriz.size}") # Total de elementos
print(f"Tipo de dado (dtype): {matriz.dtype}") # Tipos dos elementos (ex: int64, int32)

Formato (shape): (2, 3)
Dimensões (ndim): 2
Tamanho total (size): 6
Tipo de dado (dtype): int64


### 4. Operações Matemáticas Básicas

O NumPy permite fazer operações elemento a elemento de forma direta, sem a necessidade de loops for (conceito conhecido como vetorização).

In [10]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(f"Soma: {a + b}")
print(f"Subtração: {b - a}")
print(f"Multiplicação: {a * b}")
print(f"Divisão: {b / a}")

Soma: [11 22 33]
Subtração: [ 9 18 27]
Multiplicação: [10 40 90]
Divisão: [10. 10. 10.]


In [11]:
# Funções estatísticas básicas
dados = np.array([15, 20, 25, 30, 35])
print(f"Média: {np.mean(dados)}")
print(f"Desvio Padrão: {np.std(dados)}")
print(f"Valor Máximo: {np.max(dados)}")

Média: 25.0
Desvio Padrão: 7.0710678118654755
Valor Máximo: 35


### 5. Indexação e Fatiamento (Slicing)

Você pode acessar elementos específicos ou extrair subconjuntos do array.

In [12]:
arr = np.array([10, 20, 30, 40, 50])

print(f"Primeiro elemento: {arr[0]}")
print(f"Último elemento: {arr[-1]}")
print(f"Fatiamento (índice 1 ao 3): {arr[1:4]}") # O índice final é exclusivo

Primeiro elemento: 10
Último elemento: 50
Fatiamento (índice 1 ao 3): [20 30 40]


In [13]:
# Em matrizes 2D
matriz_ex = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(f"\nMatriz completa:\n {matriz_ex}")
print(f"\nElemento na linha 1, coluna 2: {matriz_ex[1,2]}")
print(f"\nTodas as linhas, apenas coluna 1:\n {matriz_ex[:, 1]}")


Matriz completa:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Elemento na linha 1, coluna 2: 60

Todas as linhas, apenas coluna 1:
 [20 50 80]
